### ISSUE TITLE
WARNING: No kernel memory limit support

### ISSUE THREAD

**Issue by bgonz** [kalabox/kalabox#1721]
I am running: 2.1.1

iMac Late 2015
3.2 GHz Core i5
32 GB 1867 DDR3 RAM

Every time I run a kbox command from CLI I get this warning:

"WARNING: No kernel memory limit support"

The CLI still performs its said task - but it would be great to not have that show up every time. Has anyone else seen this? I tried to search the issues new and old, but came up empty.

**Comment by pirog** [comment]
@bgonz this is an issue on the docker end that i think was resolved in their latest release (which is included in our 2.1.2).

**Comment by pirog** [comment]
@bgonz def let me know if this goes away after you upgrade!

**Comment by jdleonard** [comment]
I just ran into this on a fresh install of 2.1.2

![image](https://cloud.githubusercontent.com/assets/2074112/20328429/c1b44186-ab60-11e6-8321-23380fe22d0f.png)

**Comment by pirog** [comment]
@jdleonard sad to hear. That said id post this over in the Docker for Mac queues. Luckily its just a warning so beyond being annoying it should not really interfere with anything AFAIK.

**Comment by bgonz** [comment]
Whats up @jdleonard - long time no see bud (DrupalCon Austin)! 

Sure enough Mike - it still happens for me after upgrading to 2.1.2

A quick Google search revealed others with same problem so I posed a new issue with Docker for Mac: [https://github.com/docker/for-mac/issues/955](https://github.com/docker/for-mac/issues/955)

**Comment by cleverington** [comment]
Seeing the same on a fresh install of 2.1.2, including having uninstalled / installed Docker.

<img width="229" alt="computer_details" src="https://cloud.githubusercontent.com/assets/1015474/20408357/c18ff06c-acda-11e6-99e7-c8189bf2d187.png">

**Comment by wildkatana** [comment]
I'm also seeing this on the latest version.

**Comment by davidneedham** [comment]
I've seen this in the last two trainings I've been in where Kalabox is being featured. It doesn't seem to _break_ anything as far as I can tell, but it doesn't exactly inspire confidence in the students.

**Comment by pirog** [comment]
I'm sure they'll find MAMP much more inspirational. As noted before I'm
pretty sure this is an upstream docker issue so I'd post over there.

**Comment by pirog** [comment]
https://github.com/docker/for-mac/issues/955#issuecomment-262752127 looks like this will be fixed in their next stable release

**Comment by MrPaulDriver** [comment]
Confirm this is present in 2.1.3

**Comment by pirog** [comment]
@MrPaulDriver makes sense. I think we are waiting for the fix on the docker end still.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
