### ISSUE TITLE
Crash on starting fresh app

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#693]
I have did not have this problem on my other environment, but on only one specific one.
I did kbox create pantheon, everything seems fine until the end, after the rsync I see this error:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:139:15)
    at ReadStream.Stream.pipe (stream.js:96:10)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:808:23
    at tryCatcher (/usr/local/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:812:13)
```
Even with this error I get a success message:
```
###############################################################

                     BOOMSHAKALAKA!

  You have created your app with great success! Now you need
  to start that beast up which you can do by navigating to
  /Users/gremy/kalabox/apps/msdw-d7 and running `kbox start`.

  You can also start from another directory by running
 `kbox msdw-d7 start`

###############################################################
```
So I proceed to start the app, I see some docker info messages then red error:
```
Error dispatching event listeners [post-start-component]: Cannot read property '3306/tcp' of null
TypeError: Cannot read property '3306/tcp' of null
    at /Users/gremy/kalabox/apps/msdw-d7/plugins/kalabox-plugin-pantheon/lib/env.js:351:49
From previous event:
    at /Users/gremy/kalabox/apps/msdw-d7/plugins/kalabox-plugin-pantheon/lib/env.js:349:10
    at /usr/local/bin/lib/core/events.js.jx:149:11
    at /usr/local/bin/lib/core/events.js.jx:148:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:132:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:129:18)
    at /usr/local/bin/lib/core/events.js.jx:108:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:100:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:232:4)
    at /usr/local/bin/lib/app.js.jx:689:24
From previous event:
    at startComponent (/usr/local/bin/lib/app.js.jx:688:4)
    at services.verify.then.then.then.then.map.concurrency (/usr/local/bin/lib/app.js.jx:735:12)
From previous event:
    at Object.exports.start (/usr/local/bin/lib/app.js.jx:734:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/start.js.jx:22:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:876:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:173:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:236:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:235:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:244:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
```

@pirog Any ideas what might cause this?

**Comment by pirog** [comment]
@gremy im not sure but @labboy0276 posted an issue for similar to this so maybe you guys can do some research on it to help point us in the right direction. Going to close the other issue and direct people over here.

**Comment by gremy** [comment]
@labboy0276 did not have this error, the one with not being able to start the app. Could you pull down msdw-d7. I think something is weird with this site's configuration.

**Comment by gremy** [comment]
I think this problem might be because Pantheon updated terminus from 0.9.1 to 0.9.2 and there might be some changes there that don't add up with our setup.

I just rebuild greenbiz, and am having the same problem. First it was a terminus problem that I fixed buy changing the terminus verision, then it was the same error as above. I'll paste it here just in case.

```
Error dispatching event listeners [post-start-component]: Cannot read property '3306/tcp' of null
TypeError: Cannot read property '3306/tcp' of null
    at /Users/gremy/kalabox/apps/greenbiz/plugins/kalabox-plugin-pantheon/lib/env.js:351:49
From previous event:
    at /Users/gremy/kalabox/apps/greenbiz/plugins/kalabox-plugin-pantheon/lib/env.js:349:10
    at /usr/local/bin/lib/core/events.js.jx:149:11
    at /usr/local/bin/lib/core/events.js.jx:148:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:132:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:129:18)
    at /usr/local/bin/lib/core/events.js.jx:108:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:100:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:232:4)
    at /usr/local/bin/lib/app.js.jx:689:24
From previous event:
    at startComponent (/usr/local/bin/lib/app.js.jx:688:4)
    at services.verify.then.then.then.then.map.concurrency (/usr/local/bin/lib/app.js.jx:735:12)
From previous event:
    at Object.exports.start (/usr/local/bin/lib/app.js.jx:734:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/start.js.jx:22:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:876:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:173:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:236:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:235:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:244:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
```

**Comment by gremy** [comment]
So I am guessing it's something about mysql because of port 3306/tcp.

**Comment by labboy0276** [comment]
Hello!

I am still getting this on 0.10.6 but it is only happening on a multidev instance for some reason:

```
files_live/apps/blackberry/cods/Curve/8900/Huddle-3.cod
files_live/apps/office/Excel/Application Files/Huddle for Excel_1_0_0_33848/PSTaskDialog.dll.deploy
files_live/apps/blackberry/cods/Pearl/8220/Huddle-2.cod
files_live/apps/office/PowerPoint/Application Files/Huddle for Powerpoint_1_0_0_33848/Huddle for Powerpoint.dll.config.deploy
files_live/apps/office/Word/Application Files/Huddle for Word_1_0_0_33848/Huddle for Word.dll.config.deploy
files_live/apps/office/Excel/Application Files/Huddle for Excel_1_0_0_33848/Huddle.Wpf.dll.deploy
files_live/.htaccess
files_live/skipped.log
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:139:15)
    at ReadStream.Stream.pipe (stream.js:96:10)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:831:23
    at tryCatcher (/usr/local/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:812:13)
```

**Comment by pirog** [comment]
This should be resolved in the 0.11.0 release on Friday
